ALTER TABLE parts ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE parts ADD COLUMN IF NOT EXISTS condition VARCHAR(255);
ALTER TABLE parts ADD COLUMN IF NOT EXISTS visible_markings TEXT;
ALTER TABLE parts ADD COLUMN IF NOT EXISTS compatible_vehicles TEXT;
ALTER TABLE parts ADD COLUMN IF NOT EXISTS source_hints TEXT;
ALTER TABLE parts ADD COLUMN IF NOT EXISTS raw_analysis TEXT;
ALTER TABLE parts ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
